const GET_ALL_COMMUNITIES = 'GET_ALL_COMMUNITIES';
const JOIN_COMMUNITY = 'JOIN_COMMUNITY';
const LEAVE_COMMUNITY = 'LEAVE_COMMUNITY';
const CHANGE_CURRENT_COMMUNITY = 'CHANGE_CURRENT_COMMUNITY';
const ADD_NEW_COMMUNITY = 'ADD_NEW_COMMUNITY';

export default {
  GET_ALL_COMMUNITIES,
  JOIN_COMMUNITY,
  LEAVE_COMMUNITY,
  CHANGE_CURRENT_COMMUNITY,
  ADD_NEW_COMMUNITY,
};
